Inteface Created
mlsanigeria/nigeria-crime-trends pull request #23
Opened 2024-10-18 09:24 UTC by hriteshMaikap

I have createad a simple UI for taking user input. Currently the predict button doesn't work, but inputs can be taken. I have added drop box wherever it was logically feasible based on the categorical values, others are taken in the form of text input. 

https://github.com/user-attachments/assets/935ccf0c-92e8-48f5-a7af-baee1c0919d5

#18

2024-10-18 18:57 UTC, Sammybams requested changes
Thank you very much for your contribution @hriteshMaikap. I would like you to edit the columns to fit in the unique values in each column of the dataset that has been represented. So what you can do is, instead of manually entering the names, reference the file in the data folder and dynamically retrieve all unique values of the columns represented for the dropdowns (categorical columns). And you added a folder `Scripts` which I believe is in error. I already tried deleting the files from it but they are quite much. Please kindly remove it and make the changes requested and this would be good to go. Amazing work Thank you.

2024-10-19 10:25 UTC, hriteshMaikap commented
I will look into the issues of scripts folder fs. For the categorical columns, say actor1, it has more than 800 categories. Some even have 5k+ categories, so do you want to include them in the drop down, inspite of thier high count? 
Please let me know, if yes, will include it. 
About Scripts folder, will check and update
![image](https://github.com/user-attachments/assets/59cde239-43c6-4dd7-8a0d-0c794cd53391)

2024-10-19 10:57 UTC, Sammybams commented
> I will look into the issues of scripts folder fs. For the categorical columns, say actor1, it has more than 800 categories. Some even have 2k+ categories (like source), so do you want to include them in the drop down, inspite of thier high count? Please let me know, if yes, will include it. About Scripts folder, will check and update ![image](https://private-user-images.githubusercontent.com/136433323/378071176-59cde239-43c6-4dd7-8a0d-0c794cd53391.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzMzU0ODgsIm5iZiI6MTcyOTMzNTE4OCwicGF0aCI6Ii8xMzY0MzMzMjMvMzc4MDcxMTc2LTU5Y2RlMjM5LTQzYzYtNGRkNy04YTBkLTBjNzk0Y2Q1MzM5MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxOVQxMDUzMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MDRhOGJmY2YxODQ1N2I5MWVkOWI0YmZmNDE4ZDYyNTUwNGNiZmM0MWU1NzQ0YTUzMTk3NzRmZDNhMDY5YjA0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.DoE2SXuMfUTHBJ5HFza532QRDkgR9CSv9ZQZuCMWfd0)

Yea, I totally understand this. What I can recommend is to make it dynamic. So to only pick the actor1 for example that have operated in a particular admin 1 and admin2. So that means you must pick admin 1 and admin2 first and then only actor1's in that subset would be displayed.

2024-10-22 11:34 UTC, hriteshMaikap commented
Yeah that sounds good to me! Just a small request, if this step of exploring the dataset is already done in any jupyter notebook, could you link it in a reply? It would really help me out and save time!

2024-10-22 11:57 UTC, Sammybams commented
> Yeah that sounds good to me! Just a small request, if this step of exploring the dataset is already done in any jupyter notebook, could you link it in a reply? It would really help me out and save time!

You can follow the implementation by @Soumyadeep-Basak [here](https://github.com/mlsanigeria/nigeria-crime-trends/experimentation_Soumyadeep_Basak)

2024-10-22 16:24 UTC, hriteshMaikap commented
I have added all the inputs dynamically. 
One additional feature is the source column, since there was a combination of input, I manipulate the inputs from the CSV, store it in a set for unqiue values only and allow user to choose mutliple sources, staying true to the input format in the CSV file. 
In case the dropdown is too long, user can type and the most relevant option will automatically be displayed. 
I hope this completes the request :D

2024-10-23 16:44 UTC, Sammybams commented on app.py
> +df = pd.read_csv("data\\Nigeria_1997-2024_Sep20.csv")
```suggestion
df = pd.read_csv("./data/Nigeria_1997-2024_Sep20.csv")
```

2024-10-23 16:45 UTC, Sammybams approved these changes
Great work @hriteshMaikap. Thank you very much for your contribution.

2024-10-23 16:45 UTC, merged